version: '3.8'

services:
  db:
    image: postgres:15
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_DB: ${NAMEDB}
      POSTGRES_USER: ${USERDB}
      POSTGRES_PASSWORD: ${PASSWORDDB}
    ports:
      - "${PORTDB}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql_scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data: